global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'hadoop-namenode'
    static_configs:
      - targets: ['namenode:9870']

  - job_name: 'hadoop-resourcemanager'
    static_configs:
      - targets: ['resourcemanager:8088']

  - job_name: 'spark-master'
    static_configs:
      - targets: ['spark-master:8080']

  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka-1:29092', 'kafka-2:29093', 'kafka-3:29094']
