apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: namenode
spec:
  type: ClusterIP
  ports:
  - port: 8020
    targetPort: 8020
    name: fs-port
  - port: 9870
    targetPort: 9870
    name: http-port
  selector:
    app: hadoop
    component: namenode
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode-ui
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: namenode
spec:
  type: NodePort
  ports:
  - port: 9870
    targetPort: 9870
    nodePort: 30870
    name: http-port
  selector:
    app: hadoop
    component: namenode
---
apiVersion: v1
kind: Service
metadata:
  name: hadoop-datanode
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: datanode
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9864
    targetPort: 9864
    name: http-port
  - port: 50020
    targetPort: 50020
    name: ipc-port
  selector:
    app: hadoop
    component: datanode
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-resourcemanager
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: resourcemanager
spec:
  type: ClusterIP
  ports:
  - port: 8088
    targetPort: 8088
    name: webapp-port
  - port: 8032
    targetPort: 8032
    name: scheduler-port
  - port: 8030
    targetPort: 8030
    name: resource-tracker-port
  - port: 8031
    targetPort: 8031
    name: admin-port
  - port: 8033
    targetPort: 8033
    name: rm-admin-port
  selector:
    app: hadoop
    component: resourcemanager
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-resourcemanager-ui
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: resourcemanager
spec:
  type: NodePort
  ports:
  - port: 8088
    targetPort: 8088
    nodePort: 30088
    name: webapp-port
  selector:
    app: hadoop
    component: resourcemanager
---
apiVersion: v1
kind: Service
metadata:
  name: yarn-nodemanager
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: nodemanager
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8042
    targetPort: 8042
    name: webapp-port
  selector:
    app: hadoop
    component: nodemanager