apiVersion: v1
kind: Service
metadata:
  name: spark-master
  namespace: hadoop-ecosystem
  labels:
    app: spark
    component: master
spec:
  type: ClusterIP
  ports:
  - port: 7077
    targetPort: 7077
    name: master-port
  - port: 8080
    targetPort: 8080
    name: webui-port
  selector:
    app: spark
    component: master
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  namespace: hadoop-ecosystem
  labels:
    app: spark
    component: master
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
    name: webui-port
  selector:
    app: spark
    component: master
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  namespace: hadoop-ecosystem
  labels:
    app: spark
    component: worker
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8081
    targetPort: 8081
    name: webui-port
  - port: 7078
    targetPort: 7078
    name: worker-port
  selector:
    app: spark
    component: worker