apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datanode1-pvc
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: datanode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      component: datanode
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: datanode2-pvc
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: datanode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 100Gi
  selector:
    matchLabels:
      component: datanode