apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: namenode-pvc
  namespace: hadoop-ecosystem
  labels:
    app: hadoop
    component: namenode
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 50Gi
  selector:
    matchLabels:
      component: namenode