version: "3.8"
services:
  spark-history:
    image: bitnami/spark:3.5
    environment:
      SPARK_MODE: history-server
      SPARK_HISTORY_OPTS: "-Dspark.history.fs.logDirectory=hdfs://namenode:8020/spark-history"
    ports:
      - "18080:18080"
    networks: [data-net]
    deploy:
      placement:
        constraints: [node.labels.role == master]

networks:
  data-net: { external: true }

