version: "3.8"
services:
  hbase-master:
    image: harisekhon/hbase
    environment:
      HBASE_ZOOKEEPER_QUORUM: "master,worker1,worker2"
    networks: [data-net, kafka-net]
    deploy:
      placement:
        constraints: [node.labels.role == master]

  hbase-regionserver:
    image: harisekhon/hbase
    command: regionserver
    environment:
      HBASE_ZOOKEEPER_QUORUM: "master,worker1,worker2"
    networks: [data-net, kafka-net]
    deploy:
      mode: global
      placement:
        constraints: [node.labels.role == worker]

networks:
  data-net: { external: true }
  kafka-net: { external: true }

