# Production environment values
# Enhanced resource requirements and high availability for production

# Override global settings for production
global:
  imageRegistry: "your-registry.com"
  imagePullPolicy: Always

# Enhanced resources for production
resources:
  master:
    memory: "8Gi"
    cpu: "4"
  worker:
    memory: "6Gi"
    cpu: "3"
    replicas: 3

# Hadoop production configuration
hadoop:
  namenode:
    resources:
      requests:
        memory: "6Gi"
        cpu: "3"
      limits:
        memory: "8Gi"
        cpu: "4"
    storage:
      size: "200Gi"
      
  datanode:
    replicas: 3
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "6Gi"
        cpu: "3"
    storage:
      size: "500Gi"
      
  resourcemanager:
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
        
  nodemanager:
    replicas: 3
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "6Gi"
        cpu: "3"

# Spark production configuration
spark:
  master:
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
        
  worker:
    replicas: 3
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "6Gi"
        cpu: "3"

# Kafka production configuration (clustered)
kafka:
  replicas: 3
  resources:
    requests:
      memory: "2Gi"
      cpu: "1"
    limits:
      memory: "4Gi"
      cpu: "2"
  storage:
    size: "200Gi"

# Zookeeper production configuration (clustered)
zookeeper:
  replicaCount: 3
  resources:
    requests:
      memory: "1Gi"
      cpu: "0.5"
    limits:
      memory: "2Gi"
      cpu: "1"
  storage:
    size: "50Gi"

# HBase production configuration
hbase:
  master:
    replicas: 2  # HA setup
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
        
  regionserver:
    replicas: 3
    resources:
      requests:
        memory: "4Gi"
        cpu: "2"
      limits:
        memory: "6Gi"
        cpu: "3"

# PostgreSQL production configuration
postgresql:
  architecture: replication  # Master-slave setup
  primary:
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    persistence:
      size: "100Gi"
  readReplicas:
    replicaCount: 1
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"

# Airflow production configuration
airflow:
  webserver:
    replicas: 2  # HA setup
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
        
  scheduler:
    replicas: 2  # HA setup
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"

# Enhanced monitoring for production
monitoring:
  prometheus:
    resources:
      requests:
        memory: "2Gi"
        cpu: "1"
      limits:
        memory: "4Gi"
        cpu: "2"
    storage:
      size: "200Gi"
    retention: "30d"
    
  grafana:
    resources:
      requests:
        memory: "1Gi"
        cpu: "0.5"
      limits:
        memory: "2Gi"
        cpu: "1"
    replicas: 2  # HA setup

# Security settings for production
security:
  enabled: true
  rbac:
    create: true
  serviceAccount:
    create: true
  networkPolicy:
    enabled: true

# Production ingress with SSL
ingress:
  enabled: true
  className: "nginx"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
  hosts:
    - host: hadoop.company.com
      paths:
        - path: /
          pathType: Prefix
          service: hadoop-namenode
          port: 9870
    - host: spark.company.com
      paths:
        - path: /
          pathType: Prefix
          service: spark-master
          port: 8080
    - host: airflow.company.com
      paths:
        - path: /
          pathType: Prefix
          service: airflow-webserver
          port: 8080
    - host: grafana.company.com
      paths:
        - path: /
          pathType: Prefix
          service: grafana
          port: 3000
  tls:
    - secretName: hadoop-ecosystem-prod-tls
      hosts:
        - hadoop.company.com
        - spark.company.com
        - airflow.company.com
        - grafana.company.com

# Enhanced persistence for production
persistence:
  storageClass: "fast-ssd"
  accessMode: ReadWriteOnce

# Backup configuration
backup:
  enabled: true
  schedule: "0 2 * * *"  # Daily at 2 AM
  retention: "30d"